import { useEffect, useState } from 'react';
import { BedDouble, Pencil, Plus } from 'lucide-react';
import { api } from './api';
import { PaymentMethods } from './PaymentMethods';
import { PermissionsSettings } from './PermissionsSettings';
import { useCan } from './usePermissions';
import { AmountInput } from './AmountInput';
import './users-settings.css';

type User = { idusuario: string; nombre: string; email: string; rol: string };
type Props = { refresh:number; user:User|null; run:(fn:()=>Promise<any>,success?:string)=>Promise<void>; initialTab:'hotel'|'usuarios'|'formas-pago'|'permisos'; onNewType?:()=>void; onEditType?:(id:string)=>void };
const Field=({label,children}:{label:string;children:React.ReactNode})=><label className="field"><span>{label}</span>{children}</label>;
const Empty=({text}:{text:string})=><div className="empty"><div className="empty-icon"><BedDouble size={23}/></div><p>{text}</p></div>;
const Modal=({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void})=><div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose}>×</button></div>{children}</div></div>;
function useLoad<T>(path:string,refresh:number){const[data,setData]=useState<T|null>(null),[error,setError]=useState('');useEffect(()=>{let live=true;api<T>(path).then(x=>live&&setData(x)).catch(e=>live&&setError(e.message));return()=>{live=false}},[path,refresh]);return{data,error}}

export function Configuration({refresh,user,run,initialTab}:Props){const[tab,setTab]=useState<'hotel'|'usuarios'|'formas-pago'|'permisos'>(initialTab);useEffect(()=>setTab(initialTab),[initialTab]);return <>{tab==='hotel'&&<HotelSettings refresh={refresh} user={user} run={run}/>} {tab==='usuarios'&&<UsersSettings refresh={refresh} run={run} currentUserId={user?.idusuario||''}/>} {tab==='formas-pago'&&<PaymentMethods refresh={refresh} run={run}/>} {tab==='permisos'&&<PermissionsSettings/>}</>}

function HotelSettings({refresh,user,run}:{refresh:number;user:User|null;run:Props['run']}){void user;const can=useCan();const{data:hotel}=useLoad<any>('/hotel',refresh),[form,setForm]=useState<any>({});useEffect(()=>{if(hotel)setForm(hotel)},[hotel]);return <div className="card"><div className="card-head"><div><span className="eyebrow">PROPIEDAD</span><h2>Datos del hotel</h2></div></div><div className="form-grid"><Field label="Nombre"><input value={form.nombre||''} onChange={e=>setForm({...form,nombre:e.target.value})}/></Field><Field label="Razón social"><input value={form.razon_social||''} onChange={e=>setForm({...form,razon_social:e.target.value})}/></Field><Field label="RUC"><input value={form.ruc||''} onChange={e=>setForm({...form,ruc:e.target.value})}/></Field><Field label="Timbrado"><input value={form.timbrado||''} onChange={e=>setForm({...form,timbrado:e.target.value})}/></Field><Field label="Establecimiento"><input value={form.establecimiento||''} onChange={e=>setForm({...form,establecimiento:e.target.value})}/></Field><Field label="Punto de expedición"><input value={form.punto_expedicion||''} onChange={e=>setForm({...form,punto_expedicion:e.target.value})}/></Field><Field label="Dirección"><input value={form.direccion||''} onChange={e=>setForm({...form,direccion:e.target.value})}/></Field><Field label="Correo"><input value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></Field></div><button className="primary-button" disabled={!can('settings.hotel')} onClick={()=>run(()=>api('/hotel',{method:'PUT',body:JSON.stringify(form)}),'Hotel actualizado')}>Guardar cambios</button></div>}

export function RoomTypesTable({refresh,onNew,onEdit,run}:{refresh:number;onNew:()=>void;onEdit:(id:string)=>void;run:Props['run']}){const can=useCan();const{data,error}=useLoad<any[]>('/tipos-habitacion/admin',refresh);return <div className="card table-card"><div className="card-head"><div><span className="eyebrow">INVENTARIO</span><h2>Tipos de habitación</h2></div>{can('room_types.form')&&<button className="primary-button" onClick={onNew}><Plus size={17}/> Nuevo tipo</button>}</div>{error&&<div className="form-error">{error}</div>}<div className="table-wrap types-table-wrap"><table className="types-table"><thead><tr><th>Nombre</th><th>Capacidad</th><th>Descripción</th><th>Activo</th><th>Acciones</th></tr></thead><tbody>{data?.map(t=><tr key={t.idtipo_habitacion} className={!t.activo?'inactive-row':''}><td><strong>{t.nombre}</strong></td><td>{t.capacidad} personas</td><td>{t.descripcion||'—'}</td><td><label className="active-toggle"><input type="checkbox" checked={Boolean(t.activo)} disabled={!can('room_types.form')} onChange={e=>run(()=>api(`/tipos-habitacion/${t.idtipo_habitacion}`,{method:'PATCH',body:JSON.stringify({activo:e.target.checked})}),e.target.checked?'Tipo activado':'Tipo desactivado')}/><span>{t.activo?'Activo':'Inactivo'}</span></label></td><td>{can('room_types.form')&&<button className="small-button" onClick={()=>onEdit(String(t.idtipo_habitacion))}><Pencil size={14}/> Editar</button>}</td></tr>)}</tbody></table>{!data?.length&&!error&&<Empty text="Todavía no hay tipos de habitación"/>}</div></div>}

export function RatesTable({refresh,onNew,onEdit,run}:{refresh:number;onNew:()=>void;onEdit:(id:string)=>void;run:Props['run']}){const can=useCan();const{data,error}=useLoad<any[]>('/tarifas/admin',refresh);return <div className="card table-card"><div className="card-head"><div><span className="eyebrow">INVENTARIO</span><h2>Tarifas</h2></div>{can('rates.form')&&<button className="primary-button" onClick={onNew}><Plus size={17}/> Nueva tarifa</button>}</div>{error&&<div className="form-error">{error}</div>}<div className="table-wrap types-table-wrap"><table className="types-table"><thead><tr><th>Nombre</th><th>Tipo de habitación</th><th>Check-in</th><th>Check-out</th><th>Precio por noche</th><th>IVA</th><th>Activo</th><th>Acciones</th></tr></thead><tbody>{data?.map(t=><tr key={t.idtarifa} className={!t.activo?'inactive-row':''}><td><strong>{t.nombre}</strong></td><td>{t.tipo}</td><td>{String(t.hora_checkin).slice(0,5)}</td><td>{String(t.hora_checkout).slice(0,5)}</td><td>{new Intl.NumberFormat('es-PY').format(Number(t.monto_gs))} ₲</td><td>{t.iva_tasa}%</td><td><label className="active-toggle"><input type="checkbox" checked={Boolean(t.activo)} disabled={!can('rates.form')} onChange={e=>run(()=>api(`/tarifas/${t.idtarifa}`,{method:'PATCH',body:JSON.stringify({activo:e.target.checked})}),e.target.checked?'Tarifa activada':'Tarifa desactivada')}/><span>{t.activo?'Activo':'Inactivo'}</span></label></td><td>{can('rates.form')&&<button className="small-button" onClick={()=>onEdit(String(t.idtarifa))}><Pencil size={14}/> Editar</button>}</td></tr>)}</tbody></table>{!data?.length&&!error&&<Empty text="Todavía no hay tarifas"/>}</div></div>}

export function EditRate({id,onClose,run,refresh}:{id:string;onClose:()=>void;run:Props['run'];refresh:number}){const{data:rates}=useLoad<any[]>('/tarifas/admin',refresh),{data:types}=useLoad<any[]>('/tipos-habitacion',refresh),existing=rates?.find(x=>String(x.idtarifa)===id),[form,setForm]=useState<any>(null);useEffect(()=>{if(existing&&!form)setForm({nombre:existing.nombre,fk_idtipo_habitacion:existing.fk_idtipo_habitacion,hora_checkin:String(existing.hora_checkin).slice(0,5),hora_checkout:String(existing.hora_checkout).slice(0,5),monto_gs:existing.monto_gs,iva_tasa:existing.iva_tasa})},[existing]);if(!form)return <Modal title="Editar tarifa" onClose={onClose}><p>Cargando…</p></Modal>;return <Modal title="Editar tarifa" onClose={onClose}><form onSubmit={e=>{e.preventDefault();run(()=>api(`/tarifas/${id}`,{method:'PATCH',body:JSON.stringify(form)}),'Tarifa actualizada')}}><div className="form-grid"><Field label="Nombre"><input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></Field><Field label="Tipo de habitación"><select required value={form.fk_idtipo_habitacion} onChange={e=>setForm({...form,fk_idtipo_habitacion:e.target.value})}>{types?.map(t=><option key={t.idtipo_habitacion} value={t.idtipo_habitacion}>{t.nombre}</option>)}</select></Field><Field label="Check-in"><input type="time" step="60" required value={form.hora_checkin} onChange={e=>setForm({...form,hora_checkin:e.target.value})}/></Field><Field label="Check-out"><input type="time" step="60" required value={form.hora_checkout} onChange={e=>setForm({...form,hora_checkout:e.target.value})}/></Field><Field label="Precio por noche (₲)"><AmountInput required value={form.monto_gs} onChange={value=>setForm({...form,monto_gs:value})}/></Field><Field label="IVA"><select value={form.iva_tasa} onChange={e=>setForm({...form,iva_tasa:Number(e.target.value)})}><option value={10}>10%</option><option value={5}>5%</option><option value={0}>Exento</option></select></Field></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button">Guardar cambios</button></div></form></Modal>}

export function FloorsTable({refresh,onNew,onEdit,run}:{refresh:number;onNew:()=>void;onEdit:(id:string)=>void;run:Props['run']}){const can=useCan();const{data,error}=useLoad<any[]>('/pisos/admin',refresh);return <div className="card table-card"><div className="card-head"><div><span className="eyebrow">INVENTARIO</span><h2>Pisos</h2></div>{can('floors.form')&&<button className="primary-button" onClick={onNew}><Plus size={17}/> Nuevo piso</button>}</div>{error&&<div className="form-error">{error}</div>}<div className="table-wrap types-table-wrap"><table className="types-table"><thead><tr><th>Número</th><th>Nombre</th><th>Activo</th><th>Acciones</th></tr></thead><tbody>{data?.map(p=><tr key={p.idpiso} className={!p.activo?'inactive-row':''}><td><strong>{p.numero}</strong></td><td>{p.nombre}</td><td><label className="active-toggle"><input type="checkbox" checked={Boolean(p.activo)} disabled={!can('floors.form')} onChange={e=>run(()=>api(`/pisos/${p.idpiso}`,{method:'PATCH',body:JSON.stringify({activo:e.target.checked})}),e.target.checked?'Piso activado':'Piso desactivado')}/><span>{p.activo?'Activo':'Inactivo'}</span></label></td><td>{can('floors.form')&&<button className="small-button" onClick={()=>onEdit(String(p.idpiso))}><Pencil size={14}/> Editar</button>}</td></tr>)}</tbody></table>{!data?.length&&!error&&<Empty text="Todavía no hay pisos"/>}</div></div>}

export function EditFloor({id,onClose,run,refresh}:{id:string;onClose:()=>void;run:Props['run'];refresh:number}){const{data}=useLoad<any[]>('/pisos/admin',refresh),existing=data?.find(x=>String(x.idpiso)===id),[form,setForm]=useState<any>(null);useEffect(()=>{if(existing&&!form)setForm({numero:existing.numero,nombre:existing.nombre})},[existing]);if(!form)return <Modal title="Editar piso" onClose={onClose}><p>Cargando…</p></Modal>;return <Modal title="Editar piso" onClose={onClose}><form onSubmit={e=>{e.preventDefault();run(()=>api(`/pisos/${id}`,{method:'PATCH',body:JSON.stringify(form)}),'Piso actualizado')}}><div className="form-grid"><Field label="Número"><input type="number" min="1" step="1" required value={form.numero} onChange={e=>setForm({...form,numero:e.target.value})}/></Field><Field label="Nombre"><input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></Field></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button">Guardar cambios</button></div></form></Modal>}

export function RoomsTable({refresh,onNew,onEdit,run}:{refresh:number;onNew:()=>void;onEdit:(id:string)=>void;run:Props['run']}){const can=useCan();const{data,error}=useLoad<any[]>('/habitaciones/admin',refresh);return <div className="card table-card"><div className="card-head"><div><span className="eyebrow">INVENTARIO</span><h2>Administración de habitaciones</h2></div>{can('rooms.form')&&<button className="primary-button" onClick={onNew}><Plus size={17}/> Nueva habitación</button>}</div>{error&&<div className="form-error">{error}</div>}<div className="table-wrap types-table-wrap"><table className="types-table"><thead><tr><th>Número</th><th>Piso</th><th>Tipo de habitación</th><th>Tarifa</th><th>Activo</th><th>Fuera de servicio</th><th>Acciones</th></tr></thead><tbody>{data?.map(r=><tr key={r.idhabitacion} className={!r.activo?'inactive-row':''}><td><strong>{r.numero}</strong></td><td>Piso {r.piso_numero} · {r.piso_nombre}</td><td>{r.tipo}</td><td>{r.tarifa||"—"}</td><td><label className="active-toggle"><input type="checkbox" checked={Boolean(r.activo)} disabled={!can('rooms.form')} onChange={e=>run(()=>api(`/habitaciones/${r.idhabitacion}`,{method:'PATCH',body:JSON.stringify({activo:e.target.checked})}),e.target.checked?'Habitación activada':'Habitación desactivada')}/><span>{r.activo?'Activo':'Inactivo'}</span></label></td><td><label className="active-toggle"><input type="checkbox" checked={Boolean(r.fuera_servicio)} disabled={!can('rooms.form')} onChange={e=>run(()=>api(`/habitaciones/${r.idhabitacion}`,{method:'PATCH',body:JSON.stringify({fuera_servicio:e.target.checked})}),e.target.checked?'Habitación fuera de servicio':'Habitación en servicio')}/><span>{r.fuera_servicio?'Sí':'No'}</span></label></td><td>{can('rooms.form')&&<button className="small-button" onClick={()=>onEdit(String(r.idhabitacion))}><Pencil size={14}/> Editar</button>}</td></tr>)}</tbody></table>{!data?.length&&!error&&<Empty text="Todavía no hay habitaciones"/>}</div></div>}

export function EditRoom({id,onClose,run,refresh}:{id:string;onClose:()=>void;run:Props['run'];refresh:number}){const{data:rooms}=useLoad<any[]>('/habitaciones/admin',refresh),{data:types}=useLoad<any[]>('/tipos-habitacion',refresh),{data:floors}=useLoad<any[]>('/pisos',refresh),{data:rates}=useLoad<any[]>('/tarifas',refresh),existing=rooms?.find(x=>String(x.idhabitacion)===id),[form,setForm]=useState<any>(null);useEffect(()=>{if(existing&&!form)setForm({numero:existing.numero,fk_idpiso:existing.fk_idpiso,fk_idtipo_habitacion:existing.fk_idtipo_habitacion,fk_idtarifa:existing.fk_idtarifa})},[existing]);if(!form)return <Modal title="Editar habitación" onClose={onClose}><p>Cargando…</p></Modal>;return <Modal title="Editar habitación" onClose={onClose}><form onSubmit={e=>{e.preventDefault();run(()=>api(`/habitaciones/${id}`,{method:'PATCH',body:JSON.stringify(form)}),'Habitación actualizada')}}><div className="form-grid"><Field label="Número"><input required value={form.numero} onChange={e=>setForm({...form,numero:e.target.value})}/></Field><Field label="Piso"><select required value={form.fk_idpiso} onChange={e=>setForm({...form,fk_idpiso:e.target.value})}>{floors?.map(p=><option key={p.idpiso} value={p.idpiso}>Piso {p.numero} · {p.nombre}</option>)}</select></Field><Field label="Tipo"><select required value={form.fk_idtipo_habitacion} onChange={e=>setForm({...form,fk_idtipo_habitacion:e.target.value})}>{types?.map(t=><option key={t.idtipo_habitacion} value={t.idtipo_habitacion}>{t.nombre}</option>)}</select></Field><Field label="Tarifa"><select required value={form.fk_idtarifa} onChange={e=>setForm({...form,fk_idtarifa:e.target.value})}>{rates?.filter(r=>r.fk_idtipo_habitacion===form.fk_idtipo_habitacion).map(r=><option key={r.idtarifa} value={r.idtarifa}>{r.nombre} · {new Intl.NumberFormat('es-PY').format(Number(r.monto_gs))} ₲</option>)}</select></Field></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button">Guardar cambios</button></div></form></Modal>}

type UserAccount=User&{activo:boolean};
const userRoles=[['administracion','Administración'],['recepcion','Recepción'],['caja','Caja'],['limpieza','Limpieza']] as const;

function UsersSettings({refresh,run,currentUserId}:{refresh:number;run:Props['run'];currentUserId:string}){
  const {data:users,error:loadError}=useLoad<UserAccount[]>('/usuarios',refresh);
  const [creating,setCreating]=useState(false),[editing,setEditing]=useState<UserAccount|null>(null);
  const [newUser,setNewUser]=useState({nombre:'',email:'',password:'',rol:'recepcion'});
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
  const [role,setRole]=useState('recepcion'),[active,setActive]=useState(true);
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const openEdit=(account:UserAccount)=>{setEditing(account);setName(account.nombre);setEmail(account.email);setPassword('');setRole(account.rol);setActive(account.activo);setError('')};
  const close=()=>{if(!busy){setCreating(false);setEditing(null);setError('')}};
  const create=async(event:React.FormEvent)=>{
    event.preventDefault();setBusy(true);setError('');
    try{
      await api('/usuarios',{method:'POST',body:JSON.stringify(newUser)});
      setCreating(false);setNewUser({nombre:'',email:'',password:'',rol:'recepcion'});
      await run(async()=>{},'Usuario creado');
    }catch(cause:any){setError(cause.message||'No se pudo crear el usuario')}
    finally{setBusy(false)}
  };
  const update=async(event:React.FormEvent)=>{
    event.preventDefault();if(!editing)return;
    setBusy(true);setError('');
    try{
      const updated=await api<UserAccount>(`/usuarios/${editing.idusuario}`,{method:'PATCH',body:JSON.stringify({nombre:name,email,password,rol:role,activo:active})});
      setEditing(null);await run(async()=>{},'Usuario actualizado');
      if(String(editing.idusuario)===String(currentUserId)){
        let session:Partial<User>={};try{session=JSON.parse(localStorage.getItem('pms_user')||'{}')}catch{}
        localStorage.setItem('pms_user',JSON.stringify({...session,nombre:updated.nombre,email:updated.email,rol:updated.rol}));
        window.dispatchEvent(new CustomEvent('pms-user-updated',{detail:updated}));
      }
    }catch(cause:any){setError(cause.message||'No se pudo actualizar el usuario')}
    finally{setBusy(false)}
  };
  return <>
    <section className="card table-card users-settings">
      <div className="card-head"><div><span className="eyebrow">EQUIPO</span><h2>Usuarios</h2></div><button className="primary-button" onClick={()=>{setError('');setCreating(true)}}><Plus size={17}/> Nuevo usuario</button></div>
      {loadError&&<div className="form-error" role="alert">{loadError}</div>}
      <div className="table-wrap types-table-wrap"><table className="types-table users-table"><thead><tr><th>Usuario</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
        {users?.map(account=><tr key={account.idusuario} className={!account.activo?'inactive-row':''}><td><div className="user-name-cell"><div className="row-avatar">{account.nombre.slice(0,1).toUpperCase()}</div><strong>{account.nombre}</strong>{String(account.idusuario)===String(currentUserId)&&<span className="user-self-label">Tu cuenta</span>}</div></td><td>{account.email}</td><td>{userRoles.find(([key])=>key===account.rol)?.[1]||account.rol}</td><td><span className={'badge '+(account.activo?'status-en_casa':'status-cancelada')}>{account.activo?'Activo':'Inactivo'}</span></td><td><button className="small-button" onClick={()=>openEdit(account)}><Pencil size={14}/> Editar</button></td></tr>)}
      </tbody></table>{users?.length===0&&<Empty text="Todavía no hay usuarios"/>}</div>
    </section>
    {creating&&<Modal title="Nuevo usuario" onClose={close}><form onSubmit={create}><div className="form-grid"><Field label="Nombre"><input required autoFocus value={newUser.nombre} onChange={event=>setNewUser({...newUser,nombre:event.target.value})}/></Field><Field label="Correo"><input required type="email" value={newUser.email} onChange={event=>setNewUser({...newUser,email:event.target.value})}/></Field><Field label="Contraseña inicial"><input required type="password" minLength={10} value={newUser.password} onChange={event=>setNewUser({...newUser,password:event.target.value})}/></Field><Field label="Rol"><select value={newUser.rol} onChange={event=>setNewUser({...newUser,rol:event.target.value})}>{userRoles.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="ghost-button" disabled={busy} onClick={close}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?'Guardando…':'Crear usuario'}</button></div></form></Modal>}
    {editing&&<Modal title="Editar usuario" onClose={close}><form onSubmit={update}><div className="user-edit-summary"><div className="row-avatar">{editing.nombre.slice(0,1).toUpperCase()}</div><div><strong>{editing.nombre}</strong><small>{editing.email}</small></div></div><div className="form-grid"><Field label="Nombre"><input required autoFocus value={name} onChange={event=>setName(event.target.value)}/></Field><Field label="Correo"><input required type="email" value={email} onChange={event=>setEmail(event.target.value)}/></Field><Field label="Nueva contraseña (opcional)"><input type="password" minLength={10} value={password} placeholder="Dejar en blanco para conservarla" onChange={event=>setPassword(event.target.value)}/></Field><Field label="Rol"><select value={role} onChange={event=>setRole(event.target.value)}>{userRoles.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field><Field label="Estado"><select value={active?'activo':'inactivo'} onChange={event=>setActive(event.target.value==='activo')}><option value="activo">Activo</option><option value="inactivo">Inactivo</option></select></Field></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="ghost-button" disabled={busy} onClick={close}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></div></form></Modal>}
  </>;
}

export function EditRoomType({id,onClose,run,refresh}:{id:string;onClose:()=>void;run:Props['run'];refresh:number}){const{data}=useLoad<any[]>(`/tipos-habitacion/admin`,refresh),existing=data?.find((x:any)=>String(x.idtipo_habitacion)===id),[form,setForm]=useState<any>(null);useEffect(()=>{if(existing&&!form)setForm({nombre:existing.nombre,capacidad:existing.capacidad,descripcion:existing.descripcion||''})},[existing]);if(!form)return <Modal title="Editar tipo de habitación" onClose={onClose}><p>Cargando…</p></Modal>;return <Modal title="Editar tipo de habitación" onClose={onClose}><form onSubmit={e=>{e.preventDefault();run(()=>api(`/tipos-habitacion/${id}`,{method:'PATCH',body:JSON.stringify(form)}),'Tipo actualizado')}}><div className="form-grid"><Field label="Nombre"><input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></Field><Field label="Capacidad"><input type="number" min="1" required value={form.capacidad} onChange={e=>setForm({...form,capacidad:e.target.value})}/></Field></div><Field label="Descripción"><textarea value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></Field><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button">Guardar cambios</button></div></form></Modal>}
