import { useState } from 'react';
import { Area, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { gs } from './api';
import { PurchaseFilters, filterQuery, initialFilters, usePurchaseData, type Options } from './Purchases';
import './sales-analytics.css';

type Group={id:string;nombre:string;total_gs:string;cantidad:number};
type Analysis={resumen:{total_gs:string;unidades:number;cantidad:number;promedio_gs:string;pagado_gs:string;saldo_gs:string;anuladas:number;anuladas_gs:string};dias:{fecha:string;total_gs:string;cantidad:number}[];proveedores:Group[];productos:Group[];formas_pago:Group[]};
const colors=['#315849','#b97550','#d8a668','#839b87','#8d7470','#557b9b'];
const compact=(n:number)=>'₲ '+new Intl.NumberFormat('es-PY',{notation:'compact',maximumFractionDigits:1}).format(n);
const money=(n:unknown)=>gs(Math.round(Number(n)||0));
const tooltipStyle={borderRadius:9,border:'1px solid #e1e7df',fontSize:12};
function Ranking({title,rows}:{title:string;rows:Group[]}){const data=rows.slice(0,10).map(r=>({...r,total:Number(r.total_gs)}));return <section className="card sales-chart-card"><div className="sales-chart-heading"><h2>{title}</h2></div><div style={{height:Math.max(270,data.length*37)}} role="img" aria-label={title}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{right:12}}><CartesianGrid horizontal={false} stroke="#e8eee8"/><XAxis type="number" tickFormatter={compact} tick={{fontSize:11}}/><YAxis type="category" dataKey="nombre" width={115} tick={{fontSize:11}} tickFormatter={v=>String(v).length>17?String(v).slice(0,16)+'…':v}/><Tooltip contentStyle={tooltipStyle} formatter={money}/><Bar dataKey="total" name="Comprado" fill={colors[0]} radius={[0,4,4,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div></section>}
export function PurchaseAnalysis({refresh}:{refresh:number}){
  const [filters,setFilters]=useState(initialFilters),options=usePurchaseData<Options>('/compras/opciones',refresh),valid=!!filters.desde&&!!filters.hasta&&filters.desde<=filters.hasta;
  const result=usePurchaseData<Analysis>(valid?'/compras/analisis?'+filterQuery(filters):null,refresh),data=result.data;
  const daily=data?.dias.map(d=>({...d,total:Number(d.total_gs)}))||[],methods=data?.formas_pago.map(m=>({...m,total:Number(m.total_gs)}))||[];
  return <div className="sales-analytics purchase-analysis"><div className="page-head"><div><span className="eyebrow">COMPRA · ANÁLISIS</span><h1>Análisis de compra</h1><p>Costos, proveedores y pagos de las compras vigentes.</p></div></div><PurchaseFilters filters={filters} onChange={setFilters} options={options.data} analysis/>
    {!valid&&<div className="form-error">Seleccioná un período válido.</div>}{(result.error||options.error)&&<div className="form-error">{result.error||options.error}</div>}{result.loading&&<div className="card empty">Cargando análisis…</div>}
    {data&&<><div className="sales-kpi-grid">{[['Importe comprado',gs(data.resumen.total_gs)],['Unidades',data.resumen.unidades.toLocaleString('es-PY')],['Compras',data.resumen.cantidad.toLocaleString('es-PY')],['Promedio por compra',gs(data.resumen.promedio_gs)],['Pagado',gs(data.resumen.pagado_gs)],['Saldo pendiente',gs(data.resumen.saldo_gs)]].map(([name,value])=><div key={name} className="card sales-kpi"><span>{name}</span><strong>{value}</strong></div>)}</div><div className="card expense-notice">Compras anuladas del período: <strong>{data.resumen.anuladas} · {gs(data.resumen.anuladas_gs)}</strong>. Excluidas de los totales y gráficos.</div>
      {!data.resumen.cantidad?<div className="card empty">No hay compras vigentes en el período seleccionado.</div>:<><section className="card sales-chart-card"><div className="sales-chart-heading"><h2>Compras por día</h2></div><div className="sales-chart" role="img" aria-label="Importe y cantidad de compras por día"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={daily} margin={{left:8,right:10,top:14,bottom:4}}><CartesianGrid stroke="#e8eee8" vertical={false}/><XAxis dataKey="fecha" tickFormatter={v=>v.slice(8,10)+'/'+v.slice(5,7)} tick={{fontSize:11}} minTickGap={25}/><YAxis yAxisId="money" tickFormatter={compact} width={75} tick={{fontSize:11}}/><YAxis yAxisId="count" orientation="right" allowDecimals={false} width={30}/><Tooltip contentStyle={tooltipStyle} formatter={(v,name)=>name==='Importe'?money(v):Number(v).toLocaleString('es-PY')}/><Legend/><Area yAxisId="money" dataKey="total" name="Importe" stroke={colors[0]} fill="#e3eee7" strokeWidth={2} isAnimationActive={false}/><Line yAxisId="count" dataKey="cantidad" name="Compras" stroke={colors[1]} dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div></section><div className="sales-chart-grid"><Ranking title="Por proveedor" rows={data.proveedores}/><Ranking title="Por producto" rows={data.productos}/></div><section className="card sales-chart-card"><div className="sales-chart-heading"><h2>Pagos por forma de pago</h2></div><div className="sales-chart sales-chart-pie" role="img" aria-label="Pagos por forma de pago"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={methods} nameKey="nombre" dataKey="total" innerRadius="48%" outerRadius="75%" isAnimationActive={false}>{methods.map((m,i)=><Cell key={m.id} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={money}/></PieChart></ResponsiveContainer></div><div className="expense-breakdown">{data.formas_pago.map(m=><div key={m.id}><span>{m.nombre}</span><strong>{gs(m.total_gs)}</strong></div>)}</div></section></>}
    </>}
  </div>;
}
