export const ROLES=['administracion','recepcion','caja','limpieza'] as const;
export type Role=typeof ROLES[number];
type Event={key:string;group:string;label:string;defaults:readonly Role[]};
const R:Role[]=['recepcion'], C:Role[]=['caja'], L:Role[]=['limpieza'];
const RC:Role[]=[...R,...C], RL:Role[]=[...R,...L], RCL:Role[]=[...R,...C,...L];

// Administration receives every event on migration. Other defaults reproduce current access.
export const EVENTS:readonly Event[]=[
  {key:'dashboard.view',group:'General',label:'Tablero',defaults:RC},
  {key:'calendar.view',group:'General',label:'Calendario',defaults:R},
  {key:'reservations.list',group:'Reservas',label:'Listado de reservas',defaults:RC},
  {key:'reservations.create',group:'Reservas',label:'Nueva reserva',defaults:R},
  {key:'reservations.financial_detail',group:'Reservas',label:'Detalle y cuenta de reserva',defaults:RC},
  {key:'reservations.stay_detail',group:'Reservas',label:'Detalle de estadía para limpieza',defaults:L},
  {key:'reservations.transfer',group:'Reservas',label:'Cambiar habitación',defaults:R},
  {key:'reservations.checkin',group:'Reservas',label:'Registrar entrada',defaults:R},
  {key:'reservations.checkout',group:'Reservas',label:'Registrar salida',defaults:R},
  {key:'reservations.cancel',group:'Reservas',label:'Cancelar reserva',defaults:R},
  {key:'reservations.charge',group:'Reservas',label:'Agregar cargo',defaults:RC},
  {key:'reservations.payment',group:'Reservas',label:'Registrar pago',defaults:C},
  {key:'reservations.annul_payment',group:'Reservas',label:'Anular pago',defaults:C},
  {key:'rooms.list',group:'Habitaciones',label:'Habitaciones',defaults:RL},
  {key:'rooms.analysis',group:'Habitaciones',label:'Análisis de habitaciones',defaults:R},
  {key:'rooms.admin',group:'Habitaciones',label:'Administrar habitaciones',defaults:[]},
  {key:'rooms.form',group:'Habitaciones',label:'Crear y editar habitación',defaults:[]},
  {key:'room_types.list',group:'Habitaciones',label:'Tipos de habitación',defaults:R},
  {key:'room_types.form',group:'Habitaciones',label:'Crear y editar tipo',defaults:[]},
  {key:'rates.list',group:'Habitaciones',label:'Tarifas',defaults:R},
  {key:'rates.form',group:'Habitaciones',label:'Crear y editar tarifa',defaults:[]},
  {key:'floors.list',group:'Habitaciones',label:'Pisos',defaults:[]},
  {key:'floors.form',group:'Habitaciones',label:'Crear y editar piso',defaults:[]},
  {key:'guests.list',group:'Huéspedes',label:'Huéspedes e historial',defaults:RC},
  {key:'guests.form',group:'Huéspedes',label:'Crear y editar huésped',defaults:R},
  {key:'housekeeping.list',group:'Limpieza',label:'Tareas de limpieza',defaults:RL},
  {key:'housekeeping.form',group:'Limpieza',label:'Crear y actualizar tarea',defaults:RL},
  {key:'cash.current',group:'Caja',label:'Caja actual',defaults:C},
  {key:'cash.open',group:'Caja',label:'Abrir caja',defaults:C},
  {key:'cash.close',group:'Caja',label:'Cerrar caja',defaults:C},
  {key:'cash.history',group:'Caja',label:'Cajas cerradas y tickets',defaults:C},
  {key:'sales.new',group:'Ventas',label:'Nueva venta',defaults:RC},
  {key:'sales.history',group:'Ventas',label:'Historial de ventas',defaults:RC},
  {key:'sales.analysis',group:'Ventas',label:'Análisis de ventas',defaults:RC},
  {key:'sales.categories',group:'Ventas',label:'Categorías',defaults:RC},
  {key:'sales.category_form',group:'Ventas',label:'Crear y editar categoría',defaults:RC},
  {key:'sales.products',group:'Ventas',label:'Productos',defaults:RC},
  {key:'sales.product_form',group:'Ventas',label:'Crear y editar producto',defaults:RC},
  {key:'sales.inventory',group:'Ventas',label:'Inventario',defaults:RC},
  {key:'sales.inventory_adjust',group:'Ventas',label:'Ajustar inventario',defaults:RC},
  {key:'sales.annul',group:'Ventas',label:'Anular venta',defaults:C},
  {key:'purchases.list',group:'Compras',label:'Compras',defaults:C},
  {key:'purchases.new',group:'Compras',label:'Nueva compra',defaults:C},
  {key:'purchases.payment',group:'Compras',label:'Registrar pago de compra',defaults:C},
  {key:'purchases.annul',group:'Compras',label:'Anular compra',defaults:C},
  {key:'purchases.suppliers',group:'Compras',label:'Proveedores',defaults:[]},
  {key:'purchases.supplier_form',group:'Compras',label:'Crear y editar proveedor',defaults:[]},
  {key:'purchases.analysis',group:'Compras',label:'Análisis de compras',defaults:[]},
  {key:'expenses.list',group:'Gastos',label:'Gastos',defaults:C},
  {key:'expenses.new',group:'Gastos',label:'Nuevo gasto',defaults:C},
  {key:'expenses.annul',group:'Gastos',label:'Anular gasto',defaults:C},
  {key:'expenses.types',group:'Gastos',label:'Tipos de gasto',defaults:[]},
  {key:'expenses.type_form',group:'Gastos',label:'Crear y editar tipo de gasto',defaults:[]},
  {key:'expenses.analysis',group:'Gastos',label:'Análisis de gastos',defaults:[]},
  {key:'invoices.list',group:'Facturación',label:'Facturas y KuDE',defaults:RC},
  {key:'invoices.manage',group:'Facturación',label:'Emitir y gestionar facturas',defaults:C},
  {key:'reports.occupancy',group:'Informes',label:'Informe de ocupación',defaults:R},
  {key:'settings.hotel',group:'Configuración',label:'Datos del hotel',defaults:[]},
  {key:'settings.users',group:'Configuración',label:'Usuarios y roles',defaults:[]},
  {key:'settings.payment_methods',group:'Configuración',label:'Formas de pago',defaults:[]},
  {key:'settings.permissions',group:'Configuración',label:'Permisos por rol',defaults:[]},
];
export type EventKey=typeof EVENTS[number]['key'];

// A shared read endpoint accepts any listed event. Mutations use a single event.
export const ROUTE_EVENTS:Record<string,Record<string,string[]>>={
  PmsController:{
    hotel:['settings.hotel'],saveHotel:['settings.hotel'],users:['settings.users'],createUser:['settings.users'],userState:['settings.users'],
    roomTypes:['rooms.list','room_types.list','room_types.form','reservations.create'],paymentMethods:['reservations.payment','sales.new','purchases.new','purchases.payment','expenses.new'],paymentMethodsAdmin:['settings.payment_methods'],createPaymentMethod:['settings.payment_methods'],updatePaymentMethod:['settings.payment_methods'],
    roomTypesAdmin:['room_types.list'],createRoomType:['room_types.form'],updateRoomType:['room_types.form'],deleteRoomType:['room_types.form'],
    floors:['rooms.list','rooms.form','reservations.create'],floorsAdmin:['floors.list'],createFloor:['floors.form'],updateFloor:['floors.form'],
    rooms:['rooms.list','calendar.view','reservations.create','housekeeping.list','dashboard.view'],roomsAdmin:['rooms.admin'],roomsAnalysis:['rooms.analysis'],createRoom:['rooms.form'],updateRoom:['rooms.form','housekeeping.form'],
    rates:['rooms.list','rates.list','rooms.form','reservations.create','reservations.transfer'],ratesAdmin:['rates.list'],createRate:['rates.form'],updateRate:['rates.form'],
    clients:['guests.list','reservations.list','reservations.create'],clientReservations:['guests.list'],createClient:['guests.form'],updateClient:['guests.form'],
    availability:['calendar.view','reservations.create','reservations.transfer'],calendar:['calendar.view'],reservations:['reservations.list','calendar.view','dashboard.view'],reservation:['reservations.financial_detail','reservations.stay_detail','reservations.transfer'],createReservation:['reservations.create'],
    checkin:['reservations.checkin'],checkout:['reservations.checkout'],checkoutTicket:['reservations.financial_detail'],transferRoom:['reservations.transfer'],cancel:['reservations.cancel'],charge:['reservations.charge'],payment:['reservations.payment'],annulPayment:['reservations.annul_payment'],
    cashHistory:['cash.history'],cashTicket:['cash.history'],cashDetails:['cash.history'],cashStatus:['cash.open'],cash:['cash.current','expenses.list','expenses.new'],openCash:['cash.open'],closeCash:['cash.close'],
    housekeeping:['housekeeping.list'],createTask:['housekeeping.form'],updateTask:['housekeeping.form'],dashboard:['dashboard.view'],occupancy:['reports.occupancy'],
  },
  SalesController:{
    categories:['sales.categories','sales.new','sales.product_form'],createCategory:['sales.category_form'],updateCategory:['sales.category_form'],moveCategory:['sales.category_form'],
    products:['sales.products','sales.new','purchases.new'],createProduct:['sales.product_form'],updateProduct:['sales.product_form'],inventory:['sales.inventory'],adjust:['sales.inventory_adjust'],occupiedRooms:['sales.new'],analysis:['sales.analysis'],sales:['sales.history'],ticket:['sales.history','sales.new'],detail:['sales.history'],createSale:['sales.new'],annul:['sales.annul'],
  },
  PurchasesController:{suppliers:['purchases.suppliers','purchases.new'],createSupplier:['purchases.supplier_form'],updateSupplier:['purchases.supplier_form'],options:['purchases.list','purchases.new','purchases.analysis'],list:['purchases.list'],analysis:['purchases.analysis'],detail:['purchases.list'],create:['purchases.new'],pay:['purchases.payment'],annul:['purchases.annul']},
  ExpensesController:{types:['expenses.list','expenses.types','expenses.new','expenses.analysis'],createType:['expenses.type_form'],updateType:['expenses.type_form'],options:['expenses.list','expenses.analysis'],analysis:['expenses.analysis'],list:['expenses.list'],detail:['expenses.list'],create:['expenses.new'],annul:['expenses.annul']},
  FiscalController:{list:['invoices.list'],prepare:['invoices.manage'],detail:['invoices.list'],issue:['invoices.manage'],consult:['invoices.manage'],retry:['invoices.manage'],credit:['invoices.manage'],kude:['invoices.list']},
};
