import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { PassThrough } from 'node:stream';
import { Client } from 'pg';
import 'reflect-metadata';
import { applyMigrations } from './migration-runner';

test('ocupación de habitaciones: check-in, traslado, salida vencida y check-out', {skip:!process.env.TEST_DATABASE_URL&&'Requiere TEST_DATABASE_URL'}, async()=>{
  const client=new Client({connectionString:process.env.TEST_DATABASE_URL});await client.connect();
  const schema=`rooms_test_${Date.now()}`;let db:typeof import('./db')|undefined;
  try{
    await client.query(`CREATE SCHEMA ${schema}`);await client.query(`SET search_path TO ${schema},public`);
    await applyMigrations(client);
    const url=new URL(process.env.TEST_DATABASE_URL!);url.searchParams.set('options',`-c search_path=${schema},public`);process.env.DATABASE_URL=url.toString();
    db=await import('./db');const {PmsController}=await import('./pms');const {hotelDate}=await import('./common');const controller=new PmsController();
    const add=(day:string,n:number)=>{const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
    const today=hotelDate(),end=add(today,2);
    const user=(await client.query("INSERT INTO usuario(nombre,email,clave_hash,rol,creado_por) VALUES('Prueba','rooms@test.local','hash','administracion','Prueba') RETURNING *")).rows[0];const req={user};
    const customer=(await client.query("INSERT INTO cliente(nombre,creado_por) VALUES('Ana','Prueba') RETURNING *")).rows[0];
    const floor=(await client.query("INSERT INTO piso(numero,nombre,creado_por) VALUES(1,'Primer piso','Prueba') RETURNING *")).rows[0];
    const type=(await client.query("INSERT INTO tipo_habitacion(nombre,capacidad,creado_por) VALUES('Doble',2,'Prueba') RETURNING *")).rows[0];
    const rooms=[];
    for(const numero of ['101','102','103'])rooms.push((await client.query("INSERT INTO habitacion(numero,fk_idpiso,fk_idtipo_habitacion,creado_por) VALUES($1,$2,$3,'Prueba') RETURNING *",[numero,floor.idpiso,type.idtipo_habitacion])).rows[0]);
    const reservation=(await client.query("INSERT INTO reserva(fk_idcliente,fecha_entrada,fecha_salida,creado_por) VALUES($1,$2,$3,'Prueba') RETURNING *",[customer.idcliente,today,end])).rows[0];
    for(const room of rooms.slice(0,2))await client.query("INSERT INTO reserva_habitacion(fk_idreserva,fk_idhabitacion,fecha_entrada,fecha_salida,tarifa_noche_gs,creado_por) VALUES($1,$2,$3,$4,200000,'Prueba')",[reservation.idreserva,room.idhabitacion,today,end]);
    let list=await controller.rooms();assert.equal(list.length,3);assert.ok(list.every(r=>r.en_casa===false&&r.fk_idreserva_actual===null&&r.cliente_nombre===null&&r.cliente_apellido===null));
    await controller.checkin(reservation.idreserva,req);
    list=await controller.rooms();assert.equal(list.find(r=>r.numero==='101').en_casa,true);assert.equal(list.find(r=>r.numero==='102').en_casa,true);assert.equal(list.find(r=>r.numero==='103').en_casa,false);
    for(const number of ['101','102']){const occupied=list.find(r=>r.numero===number);assert.equal(occupied.fk_idreserva_actual,reservation.idreserva);assert.equal(occupied.cliente_nombre,'Ana');}
    const cleaningUser=(await client.query("INSERT INTO usuario(nombre,email,clave_hash,rol,creado_por) VALUES('Limpieza','cleaner@test.local','hash','limpieza','Prueba') RETURNING *")).rows[0];
    const restricted=await controller.reservation(reservation.idreserva,{user:cleaningUser});
    assert.deepEqual(Object.keys(restricted).sort(),['idreserva','cliente_nombre','cliente_apellido','fecha_entrada','fecha_salida','estado','habitaciones'].sort());
    assert.equal(restricted.habitaciones.length,2);assert.ok(restricted.habitaciones.every((h:any)=>!('tarifa_noche_gs' in h)));
    const financial=await controller.reservation(reservation.idreserva,req);assert.ok('saldo_gs' in financial&&'cargos' in financial&&'pagos' in financial&&'facturas' in financial);
    const {AuthGuard}=await import('./auth');const {JwtService}=await import('@nestjs/jwt');const {Reflector}=await import('@nestjs/core');
    const jwt=new JwtService({secret:'room-test-secret'}),guard=new AuthGuard(jwt,new Reflector());const request={headers:{authorization:`Bearer ${await jwt.signAsync({sub:cleaningUser.idusuario})}`}};
    const context=(handler:any)=>({switchToHttp:()=>({getRequest:()=>request}),getHandler:()=>handler,getClass:()=>PmsController}) as any;
    assert.equal(await guard.canActivate(context(controller.reservation)),true);
    for(const handler of [controller.roomsAnalysis,controller.checkin,controller.checkout,controller.checkoutTicket,controller.charge,controller.payment])await assert.rejects(()=>guard.canActivate(context(handler)));
    await assert.rejects(()=>controller.roomsAnalysis(end,today),/fecha hasta/);
    await client.query("UPDATE habitacion SET estado_limpieza='sucia',fuera_servicio=TRUE WHERE idhabitacion=$1",[rooms[1].idhabitacion]);
    assert.equal((await controller.rooms()).find(r=>r.numero==='102').cliente_nombre,'Ana');
    const assignment=(await client.query('SELECT idreserva_habitacion FROM reserva_habitacion WHERE fk_idhabitacion=$1 AND fk_idreserva=$2',[rooms[0].idhabitacion,reservation.idreserva])).rows[0];
    await controller.transferRoom(reservation.idreserva,{fk_idreserva_habitacion:assignment.idreserva_habitacion,fk_idhabitacion:rooms[2].idhabitacion,tarifa_noche_gs:'200000'},req);
    list=await controller.rooms();assert.equal(list.length,3);assert.equal(list.find(r=>r.numero==='101').en_casa,false);assert.equal(list.find(r=>r.numero==='101').fk_idreserva_actual,null);assert.equal(list.find(r=>r.numero==='103').en_casa,true);assert.equal(list.find(r=>r.numero==='103').fk_idreserva_actual,reservation.idreserva);
    await client.query("UPDATE reserva_habitacion SET fecha_entrada=$2,fecha_salida=$3 WHERE fk_idreserva=$1 AND estado='en_casa'",[reservation.idreserva,add(today,-3),add(today,-1)]);
    list=await controller.rooms();assert.equal(list.find(r=>r.numero==='103').en_casa,true);
    await client.query('UPDATE reserva SET activo=FALSE WHERE idreserva=$1',[reservation.idreserva]);assert.ok((await controller.rooms()).every(r=>!r.en_casa));await client.query('UPDATE reserva SET activo=TRUE WHERE idreserva=$1',[reservation.idreserva]);
    await client.query("UPDATE reserva_habitacion SET activo=FALSE WHERE fk_idhabitacion=$1 AND estado='en_casa'",[rooms[2].idhabitacion]);assert.equal((await controller.rooms()).find(r=>r.numero==='103').en_casa,false);await client.query("UPDATE reserva_habitacion SET activo=TRUE WHERE fk_idhabitacion=$1 AND estado='en_casa'",[rooms[2].idhabitacion]);
    await assert.rejects(()=>controller.checkout(reservation.idreserva,req),/saldo cero/);
    await controller.openCash({monto_inicial_gs:'0'},req);
    await client.query("INSERT INTO movimiento(fk_idreserva,tipo,descripcion,cantidad,monto_unitario_gs,fecha_servicio,creado_por) VALUES($1,'extra','Minibar',2,5000,$2,'Prueba'),($1,'descuento','Descuento de cortesía',1,2000,$2,'Prueba')",[reservation.idreserva,today]);
    const balance=(await controller.reservation(reservation.idreserva,req)).saldo_gs;
    const method=(await client.query("SELECT idforma_pago FROM forma_pago WHERE nombre='Efectivo'")).rows[0].idforma_pago;
    await controller.payment(reservation.idreserva,{fk_idforma_pago:method,monto_gs:balance,monto_alojamiento_gs:balance,monto_otros_gs:'0'},req);
    const checkout=await controller.checkout(reservation.idreserva,req);
    assert.equal(checkout.estado,'finalizada');
    assert.ok(checkout.fecha_checkout);
    const snapshot=checkout.checkout_resumen;
    assert.equal(snapshot.saldo_gs,'0');
    assert.equal(snapshot.total_gs,balance);
    assert.equal(snapshot.pagado_gs,balance);
    assert.equal(snapshot.habitaciones.length,3);
    assert.ok(snapshot.cargos.some((item:any)=>item.tipo==='descuento'&&item.importe_gs==='-2000'));
    assert.equal(snapshot.pagos.length,1);
    assert.equal(snapshot.registrado_por,'Prueba');
    await assert.rejects(()=>controller.checkout(reservation.idreserva,req),/no está en casa/);
    const output=new PassThrough() as PassThrough&{setHeader:(name:string,value:string)=>void};
    const chunks:Buffer[]=[],headers:Record<string,string>={};
    output.setHeader=(name,value)=>{headers[name]=value};
    output.on('data',(chunk:Buffer)=>chunks.push(chunk));
    const done=once(output,'end');
    await controller.checkoutTicket(String(reservation.idreserva),output);await done;
    assert.equal(headers['Content-Type'],'application/pdf');
    const pdf=Buffer.concat(chunks).toString('latin1');
    assert.match(pdf,/^%PDF-/);
    const page=pdf.match(/\/MediaBox\s*\[0 0 ([\d.]+) ([\d.]+)\]/);
    assert.ok(page);assert.ok(Math.abs(Number(page[1])-80/25.4*72)<.01);
    await client.query('UPDATE movimiento SET monto_unitario_gs=monto_unitario_gs+1 WHERE fk_idreserva=$1',[reservation.idreserva]);
    assert.deepEqual((await controller.reservation(reservation.idreserva,req)).checkout_resumen,snapshot);
    list=await controller.rooms();assert.ok(list.every(r=>r.en_casa===false&&r.cliente_nombre===null&&r.fk_idreserva_actual===null));assert.equal(list.find(r=>r.numero==='102').estado_limpieza,'sucia');assert.equal(list.find(r=>r.numero==='103').estado_limpieza,'sucia');
  }finally{if(db)await db.pool.end();await client.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await client.end();}
});
