import test from 'node:test';
import assert from 'node:assert/strict';
import { Client } from 'pg';
import { applyMigrations } from './migration-runner';

test('análisis de habitaciones separa noches, reservas y huéspedes', {skip:!process.env.TEST_DATABASE_URL&&'Requiere TEST_DATABASE_URL'}, async()=>{
  const client=new Client({connectionString:process.env.TEST_DATABASE_URL});await client.connect();
  const schema=`analysis_test_${Date.now()}`;let db:typeof import('./db')|undefined;
  try{
    await client.query(`CREATE SCHEMA ${schema}`);await client.query(`SET search_path TO ${schema},public`);
    await applyMigrations(client);
    const url=new URL(process.env.TEST_DATABASE_URL!);url.searchParams.set('options',`-c search_path=${schema},public`);process.env.DATABASE_URL=url.toString();
    db=await import('./db');const {roomAnalysis}=await import('./room-analysis');
    const day=(offset:number)=>{const date=new Date();date.setUTCDate(date.getUTCDate()+offset);return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Asuncion',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)};
    const today=day(0),tomorrow=day(1),later=day(2);
    const type=(await client.query("INSERT INTO tipo_habitacion(nombre,capacidad,creado_por) VALUES('Doble',2,'Prueba') RETURNING idtipo_habitacion")).rows[0];
    const floor=(await client.query("INSERT INTO piso(numero,nombre,creado_por) VALUES(1,'Piso 1','Prueba') RETURNING idpiso")).rows[0];
    const rooms=[];
    for(const numero of ['101','102','103'])rooms.push((await client.query("INSERT INTO habitacion(numero,fk_idpiso,fk_idtipo_habitacion,fecha_creado,creado_por) VALUES($1,$2,$3,$4,'Prueba') RETURNING idhabitacion",[numero,floor.idpiso,type.idtipo_habitacion,`${today}T00:00:00-03:00`])).rows[0]);
    const guest=(await client.query("INSERT INTO cliente(nombre,creado_por) VALUES('Ana','Prueba') RETURNING idcliente")).rows[0];
    const current=(await client.query("INSERT INTO reserva(fk_idcliente,fecha_entrada,fecha_salida,estado,adultos,ninos,fecha_checkin,creado_por) VALUES($1,$2,$3,'en_casa',2,1,now(),'Prueba') RETURNING idreserva",[guest.idcliente,today,tomorrow])).rows[0];
    for(const room of rooms.slice(0,2))await client.query("INSERT INTO reserva_habitacion(fk_idreserva,fk_idhabitacion,fecha_entrada,fecha_salida,tarifa_noche_gs,estado,creado_por) VALUES($1,$2,$3,$4,100000,'en_casa','Prueba')",[current.idreserva,room.idhabitacion,today,tomorrow]);
    const future=(await client.query("INSERT INTO reserva(fk_idcliente,fecha_entrada,fecha_salida,adultos,creado_por) VALUES($1,$2,$3,1,'Prueba') RETURNING idreserva",[guest.idcliente,tomorrow,later])).rows[0];
    await client.query("INSERT INTO reserva_habitacion(fk_idreserva,fk_idhabitacion,fecha_entrada,fecha_salida,tarifa_noche_gs,creado_por) VALUES($1,$2,$3,$4,90000,'Prueba')",[future.idreserva,rooms[2].idhabitacion,tomorrow,later]);
    await client.query("INSERT INTO reserva(fk_idcliente,fecha_entrada,fecha_salida,estado,creado_por) VALUES($1,$2,$3,'cancelada','Prueba')",[guest.idcliente,tomorrow,later]);
    const forms=(await client.query("SELECT idforma_pago,nombre FROM forma_pago WHERE nombre IN ('Efectivo','Tarjeta')")).rows;
    const cash=forms.find(form=>form.nombre==='Efectivo').idforma_pago,card=forms.find(form=>form.nombre==='Tarjeta').idforma_pago;
    const paymentDate=`${today}T12:00:00-03:00`,nextPaymentDate=`${tomorrow}T12:00:00-03:00`;
    await client.query("INSERT INTO pago(fk_idreserva,fk_idforma_pago,monto_gs,fecha_creado,creado_por) VALUES($1,$2,3000,$3,'Prueba')",[current.idreserva,cash,paymentDate]);
    await client.query("INSERT INTO pago(fk_idreserva,fk_idforma_pago,monto_gs,monto_alojamiento_gs,fecha_creado,creado_por) VALUES($1,$2,80000,60000,$3,'Prueba')",[current.idreserva,card,paymentDate]);
    await client.query("INSERT INTO pago(fk_idreserva,fk_idforma_pago,monto_gs,monto_alojamiento_gs,fecha_creado,creado_por) VALUES($1,$2,20000,20000,$3,'Prueba')",[current.idreserva,cash,nextPaymentDate]);
    await client.query("INSERT INTO pago(fk_idreserva,fk_idforma_pago,monto_gs,monto_alojamiento_gs,fecha_creado,creado_por) VALUES($1,$2,5000,5000,($3::date::timestamp AT TIME ZONE 'America/Asuncion'),'Prueba')",[current.idreserva,cash,today]);
    await client.query("INSERT INTO pago(fk_idreserva,fk_idforma_pago,monto_gs,monto_alojamiento_gs,fecha_creado,creado_por) VALUES($1,$2,9000,9000,($3::date::timestamp AT TIME ZONE 'America/Asuncion')-interval '1 second','Prueba')",[current.idreserva,cash,today]);
    await client.query("INSERT INTO pago(fk_idreserva,fk_idforma_pago,clase,monto_gs,monto_alojamiento_gs,fecha_creado,creado_por) VALUES($1,$2,'devolucion',10000,10000,$3,'Prueba')",[current.idreserva,cash,nextPaymentDate]);
    await client.query("INSERT INTO pago(fk_idreserva,fk_idforma_pago,monto_gs,monto_alojamiento_gs,anulado,fecha_creado,creado_por) VALUES($1,$2,4000,4000,true,$3,'Prueba')",[current.idreserva,cash,paymentDate]);
    const sale=(await client.query("INSERT INTO venta(fk_idreserva,destino,total_gs,pagado_inicial_gs,creado_por) VALUES($1,'habitacion',7000,7000,'Prueba') RETURNING idventa",[current.idreserva])).rows[0];
    await client.query("INSERT INTO pago(fk_idreserva,fk_idventa,fk_idforma_pago,monto_gs,monto_alojamiento_gs,fecha_creado,creado_por) VALUES($1,$2,$3,7000,0,$4,'Prueba')",[current.idreserva,sale.idventa,cash,paymentDate]);
    const result=await roomAnalysis(today,later,today);
    assert.equal(result.resumen.reservas_creadas,3);
    assert.equal(result.resumen.tasa_cancelacion_pct,33.3);
    assert.equal(result.resumen.noches_realizadas,2);
    assert.equal(result.resumen.noches_previstas,3);
    assert.equal(result.resumen.adr_estimado_gs,'100000');
    assert.equal(result.resumen.titulares,1);
    assert.equal(result.resumen.adultos,3);
    assert.equal(result.resumen.ninos,1);
    assert.equal(result.dias.length,3);
    assert.equal(result.dias[0].realizadas,2);
    assert.equal(result.dias[1].previstas,1);
    assert.equal(result.resumen.cobrado_alojamiento_gs,'75000');
    assert.equal(result.resumen.sin_atribucion_gs,'3000');
    assert.equal(result.resumen.pagos_sin_atribucion,1);
    assert.deepEqual(result.cobros_diarios.map(row=>row.cobrado_alojamiento_gs),['65000','10000','0']);
    assert.deepEqual(result.formas_pago_alojamiento.map(row=>[row.nombre,row.total_gs,row.sin_atribucion_gs]),[['Tarjeta','60000','0'],['Efectivo','15000','3000']]);
    assert.equal((await roomAnalysis(today,today,today)).resumen.cobrado_alojamiento_gs,'65000');
    await client.query('UPDATE habitacion SET fuera_servicio=true WHERE idhabitacion=$1',[rooms[2].idhabitacion]);
    assert.equal((await client.query('SELECT COUNT(*)::int AS n FROM habitacion_disponibilidad_historial WHERE fk_idhabitacion=$1',[rooms[2].idhabitacion])).rows[0].n,2);
    const afterServiceChange=await roomAnalysis(today,later,today);
    assert.equal(afterServiceChange.dias[1].disponibles,2);
    assert.equal(afterServiceChange.resumen.noches_previstas,2);
  }finally{if(db)await db.pool.end();await client.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await client.end();}
});
