CREATE TABLE IF NOT EXISTS rol_app (
  clave TEXT PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE
);
INSERT INTO rol_app(clave,nombre) VALUES
  ('administracion','Administración'),('recepcion','Recepción'),('caja','Caja'),('limpieza','Limpieza')
ON CONFLICT (clave) DO NOTHING;
ALTER TABLE usuario DROP CONSTRAINT IF EXISTS usuario_rol_check;
ALTER TABLE usuario ADD CONSTRAINT usuario_rol_app_fkey FOREIGN KEY (rol) REFERENCES rol_app(clave);

CREATE TABLE IF NOT EXISTS evento_permiso (
  clave TEXT PRIMARY KEY,
  grupo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  orden INTEGER NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO evento_permiso(clave,grupo,nombre,orden) VALUES
  ('dashboard.view','General','Tablero',1),
  ('calendar.view','General','Calendario',2),
  ('reservations.list','Reservas','Listado de reservas',3),
  ('reservations.create','Reservas','Nueva reserva',4),
  ('reservations.financial_detail','Reservas','Detalle y cuenta de reserva',5),
  ('reservations.stay_detail','Reservas','Detalle de estadía para limpieza',6),
  ('reservations.transfer','Reservas','Cambiar habitación',7),
  ('reservations.checkin','Reservas','Registrar entrada',8),
  ('reservations.checkout','Reservas','Registrar salida',9),
  ('reservations.cancel','Reservas','Cancelar reserva',10),
  ('reservations.charge','Reservas','Agregar cargo',11),
  ('reservations.payment','Reservas','Registrar pago',12),
  ('reservations.annul_payment','Reservas','Anular pago',13),
  ('rooms.list','Habitaciones','Habitaciones',14),
  ('rooms.analysis','Habitaciones','Análisis de habitaciones',15),
  ('rooms.admin','Habitaciones','Administrar habitaciones',16),
  ('rooms.form','Habitaciones','Crear y editar habitación',17),
  ('room_types.list','Habitaciones','Tipos de habitación',18),
  ('room_types.form','Habitaciones','Crear y editar tipo',19),
  ('rates.list','Habitaciones','Tarifas',20),
  ('rates.form','Habitaciones','Crear y editar tarifa',21),
  ('floors.list','Habitaciones','Pisos',22),
  ('floors.form','Habitaciones','Crear y editar piso',23),
  ('guests.list','Huéspedes','Huéspedes e historial',24),
  ('guests.form','Huéspedes','Crear y editar huésped',25),
  ('housekeeping.list','Limpieza','Tareas de limpieza',26),
  ('housekeeping.form','Limpieza','Crear y actualizar tarea',27),
  ('cash.current','Caja','Caja actual',28),
  ('cash.open','Caja','Abrir caja',29),
  ('cash.close','Caja','Cerrar caja',30),
  ('cash.history','Caja','Cajas cerradas y tickets',31),
  ('sales.new','Ventas','Nueva venta',32),
  ('sales.history','Ventas','Historial de ventas',33),
  ('sales.analysis','Ventas','Análisis de ventas',34),
  ('sales.categories','Ventas','Categorías',35),
  ('sales.category_form','Ventas','Crear y editar categoría',36),
  ('sales.products','Ventas','Productos',37),
  ('sales.product_form','Ventas','Crear y editar producto',38),
  ('sales.inventory','Ventas','Inventario',39),
  ('sales.inventory_adjust','Ventas','Ajustar inventario',40),
  ('sales.annul','Ventas','Anular venta',41),
  ('purchases.list','Compras','Compras',42),
  ('purchases.new','Compras','Nueva compra',43),
  ('purchases.payment','Compras','Registrar pago de compra',44),
  ('purchases.annul','Compras','Anular compra',45),
  ('purchases.suppliers','Compras','Proveedores',46),
  ('purchases.supplier_form','Compras','Crear y editar proveedor',47),
  ('purchases.analysis','Compras','Análisis de compras',48),
  ('expenses.list','Gastos','Gastos',49),
  ('expenses.new','Gastos','Nuevo gasto',50),
  ('expenses.annul','Gastos','Anular gasto',51),
  ('expenses.types','Gastos','Tipos de gasto',52),
  ('expenses.type_form','Gastos','Crear y editar tipo de gasto',53),
  ('expenses.analysis','Gastos','Análisis de gastos',54),
  ('invoices.list','Facturación','Facturas y KuDE',55),
  ('invoices.manage','Facturación','Emitir y gestionar facturas',56),
  ('reports.occupancy','Informes','Informe de ocupación',57),
  ('settings.hotel','Configuración','Datos del hotel',58),
  ('settings.users','Configuración','Usuarios y roles',59),
  ('settings.payment_methods','Configuración','Formas de pago',60),
  ('settings.permissions','Configuración','Permisos por rol',61)
ON CONFLICT (clave) DO NOTHING;

CREATE TABLE IF NOT EXISTS rol_evento (
  rol TEXT NOT NULL REFERENCES rol_app(clave),
  evento TEXT NOT NULL REFERENCES evento_permiso(clave),
  habilitado BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (rol,evento)
);
INSERT INTO rol_evento(rol,evento,habilitado)
SELECT r.clave,d.evento,r.clave=ANY(d.roles)
FROM rol_app r CROSS JOIN (VALUES
  ('dashboard.view',ARRAY['administracion','recepcion','caja']::text[]),
  ('calendar.view',ARRAY['administracion','recepcion']::text[]),
  ('reservations.list',ARRAY['administracion','recepcion','caja']::text[]),
  ('reservations.create',ARRAY['administracion','recepcion']::text[]),
  ('reservations.financial_detail',ARRAY['administracion','recepcion','caja']::text[]),
  ('reservations.stay_detail',ARRAY['administracion','limpieza']::text[]),
  ('reservations.transfer',ARRAY['administracion','recepcion']::text[]),
  ('reservations.checkin',ARRAY['administracion','recepcion']::text[]),
  ('reservations.checkout',ARRAY['administracion','recepcion']::text[]),
  ('reservations.cancel',ARRAY['administracion','recepcion']::text[]),
  ('reservations.charge',ARRAY['administracion','recepcion','caja']::text[]),
  ('reservations.payment',ARRAY['administracion','caja']::text[]),
  ('reservations.annul_payment',ARRAY['administracion','caja']::text[]),
  ('rooms.list',ARRAY['administracion','recepcion','limpieza']::text[]),
  ('rooms.analysis',ARRAY['administracion','recepcion']::text[]),
  ('rooms.admin',ARRAY['administracion']::text[]),
  ('rooms.form',ARRAY['administracion']::text[]),
  ('room_types.list',ARRAY['administracion','recepcion']::text[]),
  ('room_types.form',ARRAY['administracion']::text[]),
  ('rates.list',ARRAY['administracion','recepcion']::text[]),
  ('rates.form',ARRAY['administracion']::text[]),
  ('floors.list',ARRAY['administracion']::text[]),
  ('floors.form',ARRAY['administracion']::text[]),
  ('guests.list',ARRAY['administracion','recepcion','caja']::text[]),
  ('guests.form',ARRAY['administracion','recepcion']::text[]),
  ('housekeeping.list',ARRAY['administracion','recepcion','limpieza']::text[]),
  ('housekeeping.form',ARRAY['administracion','recepcion','limpieza']::text[]),
  ('cash.current',ARRAY['administracion','caja']::text[]),
  ('cash.open',ARRAY['administracion','caja']::text[]),
  ('cash.close',ARRAY['administracion','caja']::text[]),
  ('cash.history',ARRAY['administracion','caja']::text[]),
  ('sales.new',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.history',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.analysis',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.categories',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.category_form',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.products',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.product_form',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.inventory',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.inventory_adjust',ARRAY['administracion','recepcion','caja']::text[]),
  ('sales.annul',ARRAY['administracion','caja']::text[]),
  ('purchases.list',ARRAY['administracion','caja']::text[]),
  ('purchases.new',ARRAY['administracion','caja']::text[]),
  ('purchases.payment',ARRAY['administracion','caja']::text[]),
  ('purchases.annul',ARRAY['administracion','caja']::text[]),
  ('purchases.suppliers',ARRAY['administracion']::text[]),
  ('purchases.supplier_form',ARRAY['administracion']::text[]),
  ('purchases.analysis',ARRAY['administracion']::text[]),
  ('expenses.list',ARRAY['administracion','caja']::text[]),
  ('expenses.new',ARRAY['administracion','caja']::text[]),
  ('expenses.annul',ARRAY['administracion','caja']::text[]),
  ('expenses.types',ARRAY['administracion']::text[]),
  ('expenses.type_form',ARRAY['administracion']::text[]),
  ('expenses.analysis',ARRAY['administracion']::text[]),
  ('invoices.list',ARRAY['administracion','recepcion','caja']::text[]),
  ('invoices.manage',ARRAY['administracion','caja']::text[]),
  ('reports.occupancy',ARRAY['administracion','recepcion']::text[]),
  ('settings.hotel',ARRAY['administracion']::text[]),
  ('settings.users',ARRAY['administracion']::text[]),
  ('settings.payment_methods',ARRAY['administracion']::text[]),
  ('settings.permissions',ARRAY['administracion']::text[])
) AS d(evento,roles)
ON CONFLICT (rol,evento) DO NOTHING;
